In [1]:
import numpy as np
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

# 1. Работа с массивами NumPy

**N. Все упражнения ниже нужно делать без использования циклов Python**

**1.** Cоздать вектор

$$(2, \frac{2^2}{2}, \ldots, \frac{2^{20}}{20})$$

Можно использовать функции [np.arange()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html), [np.ones()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)

In [4]:
# СДЕЛАНО

import numpy as np

a = np.ones(20) * 2
b = np.arange(1,21)
a = a ** b
c = a/b
print(c)

# или
a = np.arange(1, 21)
a = (lambda x: (2 ** x)/x)(a)
a

[  2.00000000e+00   2.00000000e+00   2.66666667e+00   4.00000000e+00
   6.40000000e+00   1.06666667e+01   1.82857143e+01   3.20000000e+01
   5.68888889e+01   1.02400000e+02   1.86181818e+02   3.41333333e+02
   6.30153846e+02   1.17028571e+03   2.18453333e+03   4.09600000e+03
   7.71011765e+03   1.45635556e+04   2.75941053e+04   5.24288000e+04]


array([  2.00000000e+00,   2.00000000e+00,   2.66666667e+00,
         4.00000000e+00,   6.40000000e+00,   1.06666667e+01,
         1.82857143e+01,   3.20000000e+01,   5.68888889e+01,
         1.02400000e+02,   1.86181818e+02,   3.41333333e+02,
         6.30153846e+02,   1.17028571e+03,   2.18453333e+03,
         4.09600000e+03,   7.71011765e+03,   1.45635556e+04,
         2.75941053e+04,   5.24288000e+04])

**2.** Посчитать:

$$\sum\limits_{i=0}^{5}{0.1^{3i}0.2^{4i}}$$


In [10]:
# СДЕЛАНО

## your code
a = np.ones(5)
a = 0.1 ** np.arange(0,3*6,3)
b = 0.2 ** np.arange(0,4*6,4)
c = a * b
d = c.sum()

print(d)

1.0000016


**3.** Создать нулевую матрицe $8 \times 8$, и заполнить её единицами в шахматном порядке.

In [54]:
# СДЕЛАНО

chess = np.zeros((8,8), dtype=int)
chess[0:8:2,1:8:2] = 1
chess[1:8:2,0:8:2] = 1
chess

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

**4.** Есть 5 точек в декартовой системе координат (в виде матрицы $X$ размерностью $5 \times 2$), сконвертируйте эти точки в полярную систему координат.

In [47]:
# СДЕЛАНО

X = np.random.random((5, 2))
x = X[:,0]
y = X[:,1]
r = np.hypot(x,y) #sqrt(x*x + y*y).
fi = np.arctan2(y,x) 
print(r)
print(fi)

[ 0.80038744  0.61165991  0.75173993  0.73571326  1.35947084]
[ 1.37791146  0.25511976  0.9879788   1.31671373  0.76282219]


**5.** Найдите индексы максимального элемента в случайной матрице $10 \times 10$.

Cм. [np.argmax()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.argmax.html).

In [103]:
## your code
X = np.random.random((10, 10))
result = np.argmax(X)
print('Индекс максимального =',result)
print(X)
result = [result // 10, result % 10]
print(result)


Индекс максимального = 4
[[ 0.15011215  0.58732792  0.32311853  0.50398346  0.99366411  0.00204453
   0.79996788  0.92829556  0.42989198  0.48977167]
 [ 0.42555671  0.92787772  0.75353262  0.41759432  0.83531811  0.32406788
   0.62356063  0.77531228  0.00997388  0.11945281]
 [ 0.9399397   0.08267801  0.47161176  0.86447168  0.38789798  0.57559611
   0.62527121  0.75066381  0.21689839  0.06872964]
 [ 0.38891807  0.34245577  0.06481175  0.8151441   0.30401107  0.44234608
   0.37551001  0.61686052  0.62585309  0.57053223]
 [ 0.67214656  0.93657675  0.26377353  0.54949673  0.63329671  0.70258498
   0.25427691  0.49205421  0.52616842  0.84715146]
 [ 0.93846085  0.15556061  0.27388366  0.42533276  0.23170729  0.92367978
   0.57295383  0.21647523  0.21651117  0.68340052]
 [ 0.16632621  0.04379362  0.10050406  0.58603576  0.77927272  0.35461499
   0.53753973  0.65048788  0.30306261  0.51782917]
 [ 0.22964612  0.77476553  0.08912523  0.62660975  0.03501856  0.96078365
   0.94536621  0.67139606 

**6.** Есть 10 точек ($X$) и ещё одна ($y$). Найти в $X$ ближайшую к $y$ точку.

In [65]:
# СДЕЛАНО

import scipy.spatial

X = np.random.random((10, 2))
y = np.random.random((1, 2))

## your code

D = scipy.spatial.distance.cdist(X,y) # найти расстояние от каждой точки до каждой 
index = D.argmin()
print('Расстояния =')
print(D)
print('Ближайщая точка =',index)
print('Кратчайшее растояние =', D.min())

# или
dist = (lambda x1, x2, y1, y2: np.sqrt((x2-x1) ** 2 + (y2 - y1) ** 2))(X.copy()[::, 0], y[0, 0], X.copy()[::, 1], y[0, 1])
print('\nРасстояния =',dist)
result = dist.min()
print('Кратчайшее растояние =',result)

Расстояния =
[[ 0.34645324]
 [ 0.19970179]
 [ 0.41897913]
 [ 0.84932609]
 [ 0.81039621]
 [ 0.42251309]
 [ 0.73396052]
 [ 0.86608232]
 [ 0.71637835]
 [ 0.3307545 ]]
Ближайщая точка = 1
Кратчайшее растояние = 0.199701788605

Расстояния = [ 0.34645324  0.19970179  0.41897913  0.84932609  0.81039621  0.42251309
  0.73396052  0.86608232  0.71637835  0.3307545 ]
Кратчайшее растояние = 0.199701788605


**7.** Дана функция:

$$
 \begin{cases}
    x^2 + 2x + 6, & x < 0  \\
    x + 6, & 0 \le x \le 2 \\
    x^2 + 4x - 4, & x \ge 2
 \end{cases}
$$

Постройте массив из её значений на  $-3 \le x \le 3$.

In [108]:
# СДЕЛАНО 

## your code
@np.vectorize
def func(x):
    if x < 0: return x**2 + 2*x + 6
    if 0 <= x <= 2: return x + 6
    if x > 2: return x**2 + 4*x - 4
    
a = np.arange(-3,4)
b = func(a)
print(b)

[ 9  6  5  6  7  8 17]


**8.** Из каждого элемента матрицы вычесть среднее арифметическое от всех элементов в соответствующей строке (после чего среднее значение каждой строки должно равняться нулю).

Cм. [np.mean()](http://docs.scipy.org/doc/numpy/reference/generated/numpy.mean.html).

In [240]:
# СДЕЛАНО

X = np.random.random((10, 10))


## your code
result = X - X.mean(axis=1, keepdims=True)
print(result - result.mean(axis=1, keepdims=True))
print(result.mean(axis=1, keepdims=True)) #примерно = 0


[[-0.2907975  -0.0494847   0.40066922  0.30481374 -0.22977786 -0.37029621
   0.11282535 -0.36311457 -0.06963705  0.55479958]
 [ 0.2320884   0.33513624  0.17213084 -0.34010206  0.02717534  0.28547049
  -0.34327598 -0.12863037  0.30588792 -0.54588083]
 [-0.11067936 -0.14601814  0.16003905 -0.0675522   0.32554983  0.00717053
  -0.45770778 -0.33985444  0.2277242   0.4013283 ]
 [ 0.24564412  0.01005749 -0.35068412  0.27565578  0.42708369 -0.33871089
   0.3795025  -0.21933514 -0.14063815 -0.28857527]
 [-0.16626774  0.32634274 -0.26205267  0.38340774 -0.10892081  0.41034959
  -0.01930125  0.21878734 -0.357111   -0.42523393]
 [ 0.133733    0.44827792  0.46121618 -0.47181891 -0.30409514 -0.13679722
  -0.32182448  0.45925451 -0.1810114  -0.08693447]
 [-0.25706802  0.14734417 -0.25226111  0.40340188  0.10297832  0.09791066
  -0.11989083  0.38371944 -0.13175666 -0.37437785]
 [-0.02995907 -0.39020158 -0.12704676  0.11579842  0.18901818 -0.34584273
  -0.05269559 -0.14604022  0.33994952  0.44701982]



**9.** Есть массив из 1000 чисел, полученных из генератора случайных чисел, имеющий нормальное распределение. Посчитайте выборочное среднее и выборочную дисперсию. 

In [140]:
# СДЕЛАНО

X = np.random.normal(loc=5, scale=2., size=1000)
print('mean =',X.mean(),'dispersion=',((X - X.mean())**2).mean())


mean = 5.10113270904 dispersion= 3.93242716885


**10.** Создать матрицу:

$$
\begin{pmatrix}
0 & 1 & 2 & 3 & 4 \\
1 & 2 & 3 & 4 & 0 \\
2 & 3 & 4 & 0 & 1 \\
3 & 4 & 0 & 1 & 2 \\
4 & 0 & 1 & 2 & 3
\end{pmatrix}
$$

In [161]:
# СДЕЛАНО

## your code
a = np.concatenate((np.arange(0,5),np.arange(1,5),[0],np.arange(2,5),np.arange(0,2),np.arange(3,5),np.arange(0,3),[4],np.arange(0,4)), axis=0)
b = a.reshape((5,5))
print('a =', a)
print('b =')
print(b)

a = [0 1 2 3 4 1 2 3 4 0 2 3 4 0 1 3 4 0 1 2 4 0 1 2 3]
b =
[[0 1 2 3 4]
 [1 2 3 4 0]
 [2 3 4 0 1]
 [3 4 0 1 2]
 [4 0 1 2 3]]
